### ISSUE TITLE
api call issue

### ISSUE THREAD

**Issue by OpTriumph** [OpTriumph/MiniTwitter#15]
https://ibb.co/q14Kjcb
https://ibb.co/HdpshW8
https://ibb.co/nj3tVpf

**Comment by JeongJuRyu** [comment]
첫 번째 이슈의 경우는 로그인이 된 상태여서 현재 서버 세션에 유저의 정보가 저장되어 있을 때, 해당 유저의 정보를 DB에서 찾아 돌려줍니다. 아직 로그인이 된 상태가 아니어서 null이 반환된 것 같아요
두 번째 이슈는 제가 라우트 구현을 안했습니다.. post로 get 요청..?
세 번쨰 이슈는 postman에서 데이터를 전송 해 주어야 합니다. request body에 id와 content 담아서 전송을 하면 데이터 잘 넘어옵니다(확인 완료했어요!)

**Comment by JeongJuRyu** [comment]
첫 번째 이슈 테스트하였고, 로그인 후에 해당 요청 시 정상적으로 프론트에 유저의 데이터가 전달되는 것을 확인했습니다!
![image](https://user-images.githubusercontent.com/39542775/121618228-66500e00-caa1-11eb-9634-d9d1b02dca8f.png)

**Comment by OpTriumph** [comment]
감사합니다 , 확인하겠습니다
